version: '3.9'

services:

  eleaves-app:
    restart: unless-stopped
    build:
      context: .
      target: dev-app
    volumes:
      - ./apps:/eleaves/apps
      - ./tests:/eleaves/tests
      - ./tailwind.config.js:/eleaves/tailwind.config.js
      - ./.yarn:/eleaves/.yarn
      - ./package.json:/eleaves/package.json
      - ./yarn.lock:/eleaves/yarn.lock


volumes:
  pgadmin:
