.deployment:
  stage: deploy
  image: ubuntu:latest
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script: |
    cat <<'EOT' | ssh -p $HOST_PORT github@$HOST_IP
      ./update.sh
    EOT

'Deploy to DEV':
  extends: .deployment
  environment:
    name: DEVELOPMENT
  only:
    - develop
  variables:
    HOST_IP: ${HOST_IP}
    HOST_PORT: ${HOST_PORT}
    SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
    SSH_KNOWN_HOSTS: ${SSH_KNOWN_HOSTS}

'Deploy to PROD':
  extends: .deployment
  environment:
    name: PRODUCTION
  only:
    - main
  variables:
    HOST_IP: ${HOST_IP}
    HOST_PORT: ${HOST_PORT}
    SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
    SSH_KNOWN_HOSTS: ${SSH_KNOWN_HOSTS}
