default:
  image: node:16
  before_script:
    - yarn
  cache:
    - key:
        files:
          - yarn.lock
      paths:
        - .yarn/cache/
        - .yarn/unplugged/
        - .yarn/install-state.gz
    - key: "$CI_COMMIT_REF_SLUG" # name of current branch
      paths:
        - .jest/cache
